[theme]
primaryColor="#de9627"
backgroundColor="#e7e7ef"
secondaryBackgroundColor="#f7bf6e"
textColor="#3ec50c"


[runner]
magicEnabled = False

[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000


